### ISSUE TITLE
Possible violation of in-order publishing guarantee

### ISSUE THREAD

**Issue by tschuchortdev** [tomorrow-one/transactional-outbox#39] opened 2022-11-21 13:18 UTC
Last week I was skimming over the code and this snippet caught my eye:

```
private Mono<List<OutboxRecord>> processOutbox() {
		return repository.getUnprocessedRecords(batchSize)
				.flatMap(this::publish)
				.concatMap(outboxRecord -> repository.saveInNewTransaction(
						outboxRecord.toBuilder().processed(now()).build()
				))
				.collectList();
	}
```

Without having tested it or having put too much thought into it, and I may be wrong here, I suspect that there could be a bug in this function that will publish events in the wrong order and I'm interested to hear your thoughts on it. My reasoning is as follows:

1. As far as I know, `flatMap` does not preserve the ordering of elements and executes each sub-flow in parallel (see https://stackoverflow.com/questions/71971062/whats-the-difference-between-flatmap-flatmapsequential-and-concatmap-in-project). Thus, the acknowledgement of records in the outbox database table does not necessarily happen in the order that the messages were published to Kafka, unless the Kafka producer itself takes care of this serialization. While the Kafka producer guarantees that messages are published in the same order as they were handed over to the producer, I'm not sure that this extends to the order of the callbacks when messages are send to different topics/partitions. Quote: 

> Callbacks for records being sent to the same partition are guaranteed to execute in order
https://kafka.apache.org/23/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html

If outbox records that enter the `concatMap` are no longer in-order, then a later record will be acknowledged in the outbox database table before a previous one. After a crash at this moment, the restarted service will re-publish the earlier unacknowledged record, thereby violating the in-order publishing guarantee.

  Example: `abcde|dfg` (where `|` denotes the crash and letters denote the messaged ack-ed by the Kafka broker.)

  Note that I understand "in-order publishing with duplicates" to be this

`abcddefg`

but not this

`abcdedefg` where an earlier message appears after a later message.

I recommend to replace the `flatMap` with `flatMapSequential` just to be sure. There should be no decrease in throughput as the sub-flows are still subscribed eagerly (as long as the internal buffer of the `flatMapSequential` operator is large enough). Still, the publishing of a later record in the outbox table can succeed even when a previous record of the same batch has failed since this later record is handed over the the Kafka producer before success of the previous record has been acknowledged so

> [...] if a message could not be published, it will not try to publish the next message

is not true.

2. Analogously, if the stream logic of this `flatMap` and following `concatMap` are pipelined, a later record can enter `flatMap(this::publish)` and be published to Kafka before the earlier record has exited the `concatMap(...)`, i.e. the transaction to acknowledge the record in the database has committed successfully. After a crash at this moment, both the earlier and later message will be re-published to Kafka even though the later message may have already been acknowledged by the Kafka broker, thereby again violating the in-order publishing guarantee. I'm not familiar with the Reactor implementation, but since it follows the Reactive Streams protocol I would assume that this pipelining indeed takes place; at least that is how Akka Streams works (for asynchronous operators equivalent to this `flatMap` that are not fused).

Example: `abcde|defg`

Let me know what you think.

**Comment by magro** [comment] 2022-11-21 23:12
Hi @tschuchortdev, thanks for reporting this! Based on this I realized that the `OutboxProcessorIntegrationTest` didn't do its job, which should be fixed by #41 now.

The critical thing is the setting of `max.in.flight.requests.per.connection = 1`, which is the default, and with the mentioned PR also explicitely mentioned in the README.

With this setting, I couldn't break in-order messaging with the existing test (also not with more records).

With `max.in.flight.requests.per.connection = 6` though (changed [here](https://github.com/tomorrow-one/transactional-outbox/blob/4e699ba0dc80c146e91841b755884ae684d70eac/outbox-kafka-spring-reactive/src/test/java/one/tomorrow/transactionaloutbox/reactive/service/OutboxProcessorIntegrationTest.java#L256)), the `OutboxProcessorIntegrationTest.should_processRecordsInOrder_whenKafkaIsTemporarilyNotAvailable` test gets broken regarding in-order messaging (see more details in the PR).
But then also `flatMapSequential` instead of `flatMap` doesn't help.

As I understand it, the ordering is then messed up internally in the producer I think, so it's not really related to the "surroundings" (`flatMap`/`concatMap`) I'd say.

Btw, ordering is only relevant for the same partition anyways, because across different partitions ordering cannot be guaranteed at all by Kafka, i.e. cross-partitions it's just not relevant.

If `flatMap` instead of `flatMapSequential` could be an issue, do you have an idea how a test should look like to show that issue?

**Comment by tschuchortdev** [comment] 2022-11-22 00:50
With `max.in.flight.requests.per.connection = 1` the behaviour of `flatMap` should be identical to `flatMapSequential` even across partitions as long as the Kafka producer isn't doing anything super weird. However, I believe that the Kafka producer will still publish the message asynchronously and its internal send buffer can be filled before the first callback is invoked, so a later message could be published even when a previous message failed (regardless of partitions). Perhaps it would be wise to use `concatMap` then, which waits for the sub-flow to complete before starting the next one. With only one in-flight request, the throughput and latency will be worse anyway, so performance-wise it doesn't make a difference.

> Btw, ordering is only relevant for the same partition anyways

I guess that is true. Even if messages were produced in-order across partitions/topics, consumers could not rely on this, so it is irrelevant (at least when the time between is messages is small).

> With `max.in.flight.requests.per.connection = 6` though [...] the test gets broken regarding in-order messaging [...].
> But then also flatMapSequential instead of flatMap doesn't help.
> And as I understand it, the ordering is then messed up internally in the producer

According to the docs, the Kafka producer guarantees ordering within a partition. With `flatMapSequential` the elements should always be in-order throughout the stream. Of course the actual order of publishing inside the Kafka producer can be different, but elements will be buffered and put back into original order. I don't think that the test recreates the particular scenario that I mentioned, but it doesn't matter because callback invocations preserve the ordering within a partition. 

Does your test also address the possible problem of pipelining? Out-of-order publishing due to pipelining occurs independently of producer config and within a single partition/topic.

**Comment by magro** [comment] 2022-11-22 12:13
> I believe that the Kafka producer will still publish the message asynchronously and its internal send buffer can be filled before the first callback is invoked, so a later message could be published even when a previous message failed (regardless of partitions)

Not sure why you think that "_a later message could be published even when a previous message failed_", I have a different understanding in this regard. As I see it this is exactly the point of `max.in.flight.requests.per.connection` (assuming the other related config not being messed up): with `max.in.flight.requests.per.connection = 1` the producer waits until the message got delivered and it received the confirmation (based on configured acks) before it tries the next message. The [documentation on 'max.in.flight.requests.per.connection'](https://kafka.apache.org/documentation/#producerconfigs_max.in.flight.requests.per.connection) says:
> The maximum number of unacknowledged requests the client will send on a single connection before blocking

Maybe we have a misunderstanding here or have different implicit assumptions. For me it would be helpful to understand why you think that "_a later message could be published even when a previous message failed_".

**Comment by tschuchortdev** [comment] 2022-11-22 13:35
> The producer consists of a pool of buffer space that holds records that haven't yet been transmitted to the server as well as a background I/O thread that is responsible for turning these records into requests

When you call `send` you are only handing off messages into this buffer. The actual sending happens later and `send` will only block if the buffer is already full. By using `flatMap` or `flatMapSequential` you are putting all the messages in the buffer and _then_ waiting for acknowledgement. By the time an earlier message fails, the next message is already be in the buffer. I'm assuming that the Kafka producer will continue to publish messages from the buffer after a previous message has failed, since the documentation of `send` says nothing to the contrary and it would be difficult for the caller of `send` to know what messages have already been handed off to the buffer and need application retries. Though, it can only get to that point if unlimited retries are disabled.

**Comment by magro** [comment] 2022-11-22 17:57
Thanks, ok, I think now I'm on the same page and tend to agree 🙂

At the same time I'm wondering why the test (see #41) didn't catch that, even not with retries set to 0. Do you have an idea what could explain this? Maybe the connection cuts would have to be much more frequent / with significantly shorter delays in between...?

**Comment by magro** [comment] 2022-11-24 00:14
I tried to trigger this issue by playing with different settings (for `producerProps`, much smaller `requestTimeout`, different `batchSize`, higher `numRecords` etc)  for [OutboxProcessorIntegrationTest.should_processRecordsInOrder_whenKafkaIsTemporarilyNotAvailable](https://github.com/tomorrow-one/transactional-outbox/blob/main/outbox-kafka-spring-reactive/src/test/java/one/tomorrow/transactionaloutbox/reactive/service/OutboxProcessorIntegrationTest.java#L138), but unfortunately couldn't produce the issue.
Just now I had the test running for ~10 minutes and this didn't trigger the issue.

To go forward, I'd see the following options:
1. Configure "unlimited" [retries](https://kafka.apache.org/documentation/#producerconfigs_retries) (by setting `retries` to `Integer.MAX_VALUE`), while keeping the default [delivery.timeout.ms](https://kafka.apache.org/documentation/#producerconfigs_delivery.timeout.ms) of 120 seconds
    * The `delivery.timeout.ms` would prevent the producer from being stuck in a retry loop, so that the producer eventually could be recreated
    * The assumption / hope would be that if one message cannot be delivered in that time, the next message in the batch could also not be sent (before the producer would be recreated)
    * I.e. this is not very much different than right now as I see it - trades performance / throughput against guarantees
2. Change processing of outbox records to be really sequential, i.e. invoke `producer.send()` for the next record not before `producer.send()` for the previous record was successful
    * This would be the closest to the implementation of [processOutbox() in the classic module](https://github.com/tomorrow-one/transactional-outbox/blob/b8a3b79ccd7b6fa488d45ebc92d500743605776f/outbox-kafka-spring/src/main/java/one/tomorrow/transactionaloutbox/service/OutboxProcessor.java#L168)
    * This would provide a guarantee (like 100%), would value correctness more than performance/throughput
3. Build upon [enable.idempotence](https://kafka.apache.org/documentation/#producerconfigs_enable.idempotence) to prevent out-of-order messages for the active producer
    * The [sequence check on server side](https://github.com/a0x8o/kafka/blob/master/core/src/main/scala/kafka/log/ProducerStateManager.scala#L237) seems to check if `nextSeq == lastSeq + 1L` - so that missing messages should be detected
4. Try harder to produce the assumed/expected issue
5. Challenge the understanding more, maybe something was missed

And maybe there are other options...

@tschuchortdev @tomorrow-one/transactional-outbox-maintainers WDYT?

**Comment by tschuchortdev** [comment] 2022-11-24 10:17
One possible explanation would be that `max.in.flight.requests.per.connection = 1` somehow also affects the buffer. Or maybe the test just can't reproduce the scenario correctly. If you're simply cutting the connection to the docker container, you'd have to cut it _just_ at the right moment to block the first request but allow the second request (you might be able to do that by configuring `retries=1` and  a very high `retry.backoff.ms` to have enough time between requests to toggle the connection).

I am unable to run the tests myself on my Windows PC because the message's timestamp loses precision during the serialization-deserialization round trip, which makes some of the tests fail out of the box.

> Change processing of outbox records to be really sequential, i.e. invoke producer.send() for the next record not before producer.send() for the previous record was successful. 
This would be the closest to the implementation of [processOutbox() in the classic module](https://github.com/tomorrow-one/transactional-outbox/blob/b8a3b79ccd7b6fa488d45ebc92d500743605776f/outbox-kafka-spring/src/main/java/one/tomorrow/transactionaloutbox/service/OutboxProcessor.java#L168)
This would provide a guarantee (like 100%), would value correctness more than performance/throughput

I like that this is the simplest solution and that it makes behaviour more consistent between modules. Why do you think there would be a reduction in performance? If `max.in.flight.requests.per.connection = 1` then the performance should be the same (or is more than one connection?) because the producer already limits itself to one request at a time.

> Challenge the understanding more, maybe something was missed

This would definitely be the prudent thing to do. I don't actually care about an obscure edge case in a library that I don't personally use. It's purely an exercise for better understanding of Kafka for me.

**Comment by magro** [comment] 2022-11-24 11:04
> Change processing of outbox records to be really sequential, i.e. invoke producer.send() for the next record not before producer.send() for the previous record was successful.
>> I like that this is the simplest solution and that it makes behaviour more consistent between modules. Why do you think there would be a reduction in performance? If max.in.flight.requests.per.connection = 1 then the performance should be the same (or is more than one connection?) because the producer already limits itself to one request at a time.

The producer batches multiple _records_ (coming in via `producer.send()`) into 1 _request_ (based on the configured `batch.size` with a default of 16k). Right now, if 100 records are loaded from the db and handed over to the producer, one scenario could be that e.g. "the first" record is sent with the first request, and the other 99 records are buffered and sent with the following request. I.e. max throughput _would_ be affected.

> This would definitely be the prudent thing to do. I don't actually care about an obscure edge case in a library that I don't personally use. It's purely an exercise for better understanding of Kafka for me.

:+1: :smile:

**Comment by magro** [comment] 2022-12-10 15:13
I couldn't reproduce the issue with such settings unfortunately.

After more investigation I think the idempotent producer provides the ordering guarantee we want:
> For a given PID, sequence numbers will start from zero and be monotonically increasing, with one sequence number per topic partition produced to. The sequence number will be incremented by the producer on every message sent to the broker. The broker maintains in memory the sequence numbers it receives for each topic partition from every PID. The broker will reject a produce request if its sequence number is not exactly one greater than the last committed message from that PID/TopicPartition pair. Messages with a lower sequence number result in a duplicate error, which can be ignored by the producer. Messages with a higher number result in an out-of-sequence error, which indicates that some messages have been lost, and is fatal.

(source: https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging#KIP98ExactlyOnceDeliveryandTransactionalMessaging-IdempotentProducerGuarantees)

Further reading for a broader perspective on the topic:
* https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/
* https://medium.com/@jaykreps/exactly-once-support-in-apache-kafka-55e1fdd0a35f
* https://blog.softwaremill.com/does-kafka-really-guarantee-the-order-of-messages-3ca849fd19d2
* https://softwaremill.com/what-kafka-exactly-once-really-means/

Based on that I'd propose to enforce idempotent producer config to guarantee ordering.
WDYT, @tschuchortdev @tomorrow-one/transactional-outbox-maintainers?

**Closed** 2023-07-03 21:59 UTC
